DROP TABLE IF EXISTS task_labels;
DROP TABLE IF EXISTS labels;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS columns;
DROP TABLE IF EXISTS board_users;
DROP TABLE IF EXISTS boards;
DROP TABLE IF EXISTS users;